# Generated by Django 4.1.5 on 2023-01-13 18:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountaddress_address_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaddress',
            name='country',
            field=django_countries.fields.CountryField(default='India', max_length=2),
        ),
    ]
